{% set name = "pyMaBoSS" %}
{% set version = "0.6.3" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/colomoto/pyMaBoSS.git

channels:
  - colomoto

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - colomoto_jupyter >=0.4.10
    - maboss
    - pandas
    - pyparsing
    - python
    - matplotlib
    - ipywidgets

about:
  home: https://github.com/colomoto/pyMaBoSS
  summary: 'Python API for the MaBoSS simulation software'

