{% set name = "pyMaBoSS" %}
{% set version = "0.8.2b0" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ..

channels:
  - colomoto

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - colomoto_jupyter >=0.4.10
    - maboss
    - pandas
    - pyparsing
    - python
    - matplotlib
    - ipywidgets
    - scikit-learn
    - cmaboss >=1.0.0b15

about:
  home: https://github.com/colomoto/pyMaBoSS
  summary: 'Python API for the MaBoSS simulation software'

