{% set name = "pyMaBoSS" %}
{% set version = "0.7.17" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/colomoto/pyMaBoSS.git

channels:
  - colomoto

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - colomoto_jupyter >=0.4.10
    - maboss
    - pandas
    - pyparsing
    - python
    - matplotlib
    - ipywidgets
    - scikit-learn
    - cmaboss

about:
  home: https://github.com/colomoto/pyMaBoSS
  summary: 'Python API for the MaBoSS simulation software'

